name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: amd64_arm64
          spectre: true
      - name: Download ddnet
        run: |
            Invoke-WebRequest https://github.com/DDNet-WinArm64/ddnet/archive/refs/heads/winarm64.zip -OutFile winarm64.zip
            unzip winarm64.zip
            Remove-Item -Recurse -Force ddnet-winarm64/ddnet-libs
      - name: Download ddnet-libs
        uses: actions/download-artifact@v4
        with:
            name: ddnet-libs-windows-arm64-llvm-ucrt
            path: ${{github.workspace}}/ddnet-winarm64/ddnet-libs
            github-token: ${{ secrets.GITHUB_TOKEN }}
            repository: DDNet-WinArm64/ddnet-libs
            run-id: 10107145927
      - name: Install minimal stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
      - name: Build
        run: |
            cd ddnet-winarm64
            cmake -S . -B build -A ARM64 -DCMAKE_BUILD_TYPE=Release
            cmake --build build --config Release --parallel
